from tkinter import *
root = Tk()
topFrame = Frame(root)
topFrame.pack(side=TOP)
bottomFrame = Frame(root)
bottomFrame.pack(side=BOTTOM)
button1 = Button(topFrame, text='input')
button1.config(bg='lightblue', fg='black', font=('times', 15, 'bold'))
button2 = Button(topFrame, text='save', fg='pink', bg='yellow')
button3 = Button(bottomFrame, text='cancle', fg='black', bg='white')
button1.pack(side=LEFT)
button2.pack(side=LEFT)
button3.pack()
root.mainloop()
